services:
  db:
    image: postgres:16
    container_name: cve-scanner-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CfX5680!2662Kutasd-Nordis*
      POSTGRES_DB: cveapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: